### ISSUE TITLE
Blank nodes

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/modular-led-controller-workstation#138]
I struggle a bit when creating a new config. The nodes spawn always a the bottom for me, so I have to move around, zoom out, relocate and continue spawning the next node.

I would like to have a bubble node mode, where every node spawns where the cursor hits. 
And furthermore I'd like a blank node (or deactivation option) to just pass the signal through. This would greatly improve the possibilities and speed when creating a config.

**Comment by segfault16** [comment]
@fruechtegott See #133 

When adding an effect node the graph is now stretched at the click position to make room for the new node. 
![Screen Shot 2019-11-20 at 04 29 51](https://user-images.githubusercontent.com/10546108/69206951-7fefd480-0b4e-11ea-8684-8dd4588bfab9.png)

**Comment by segfault16** [comment]
I don't get the blank nodes and don't think they'll improve UX. As for 'bypassing' an effect this is not so easy, since the number of pixels at the input don't have to match the number of pixels at the output. You could implement a general 'bypass' functionality in `Effect` and disabling it on certain effects. Feel free to create a PR, I'm happy to review.
