### ISSUE TITLE
Performance Parameter and Modulators

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/modular-led-controller-workstation#56]
Like in quartz composer, I would like to have different input ports in the effects. Related #12 

<img width="957" alt="adding an input splitter and setting the type" src="https://user-images.githubusercontent.com/18394044/52149779-33deac80-266e-11e9-8c24-aaaeec6114c4.png">

**Comment by segfault16** [comment]
I'm not sure if I'm getting this right.

Conceptually I like the idea of being able to modify not only the pixel and audio input of effects, but also control parameters of the effects with some modifiers (LFO, ADSR, Audio Gain, etc.).

Apart from adjusting the effects (we should make them more robust to changes of the parameters, so that current state is kept, see changing num_waves in SwimmingPool) this would also require fundamental changes to the UI.

I could think of adding a modulator section to the lower part of the edit screen (maybe collapsable just like the keyboard where you can insert new modulators). When a modulator is selected, the nodes whose parameters are controlled by the modulator could light up so you can see which ones are affected by the modulator. We would then need a way to visualise which parameters are controlled by the modulator and by how much.

**Comment by segfault16** [comment]
Like we discussed yesterday we could have standardised performance parameters:
- Intensity
- Speed
- ...

**Comment by segfault16** [comment]
Closed in favor of #125.
